spring:
  application:
    name: homepage-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否从Eureka Server中获取注册信息，默认为true
    # 如果是单点的Eureka Server的话，那就不需要同步其他节点的数据，所以false
    fetch-registry: false
    # 表示是否将自己注册到Eureka Server，默认为true
    # 如果是单点的Eureka Server的话，那就不需要把自身注册给其他节点的Server，所以false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
